
const Database = require('better-sqlite3');
const db = new Database('omnidrive.db');

const inventory = [
    // Cars (46)
    { id: 1, brand: "Acura", model: "NSX", price: 165000, nation: "Japan", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Hybrid", drivetrain: "AWD", bodyStyle: "Coupe", color: "Black", img: "assets/vehicles/acura-nsx.jpg", engine: "3.5L Twin Turbo Hybrid", horsepower: 573, transmission: "9-Speed DCT", availability: "In Stock", warranty: "4 Years/50k Miles", rating: 4.8 },
    { id: 2, brand: "Alfa Romeo", model: "Giulia Quadrifoglio", price: 95000, nation: "Italy", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "RWD", bodyStyle: "Sedan", color: "Red", img: "assets/vehicles/alfa-romeo-giulia.jpg", engine: "2.9L Twin Turbo V6", horsepower: 505, transmission: "8-Speed Auto", availability: "In Stock", warranty: "4 Years/50k Miles", rating: 4.7 },
    { id: 3, brand: "Aston Martin", model: "DB12", price: 245000, nation: "UK", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "RWD", bodyStyle: "Coupe", color: "Silver", img: "assets/vehicles/aston-martin-db12.jpg", engine: "5.2L Twin Turbo V12", horsepower: 680, transmission: "8-Speed Auto", availability: "Low Stock", warranty: "3 Years/Unlimited", rating: 4.9 },
    { id: 4, brand: "Bentley", model: "Continental GT", price: 215000, nation: "UK", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "AWD", bodyStyle: "Coupe", color: "Blue", img: "assets/vehicles/bentley-continental.jpg", engine: "6.0L Twin Turbo W12", horsepower: 626, transmission: "8-Speed Auto", availability: "In Stock", warranty: "3 Years/Unlimited", rating: 4.9 },
    { id: 5, brand: "BMW", model: "M5 Competition", price: 105000, nation: "Germany", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "AWD", bodyStyle: "Sedan", color: "Gray", img: "assets/vehicles/bmw-m5.jpg", engine: "4.4L Twin Turbo V8", horsepower: 617, transmission: "8-Speed Auto", availability: "In Stock", warranty: "4 Years/50k Miles", rating: 4.8 },
    { id: 6, brand: "Bugatti", model: "Chiron", price: 350000, nation: "France", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "AWD", bodyStyle: "Coupe", color: "Blue", img: "assets/vehicles/bugatti-chiron.jpg", engine: "8.0L Quad Turbo W16", horsepower: 1500, transmission: "7-Speed DCT", availability: "Pre-Order", warranty: "3 Years/Unlimited", rating: 5.0 },
    { id: 7, brand: "Buick", model: "Enclave", price: 45000, nation: "USA", category: "Car", condition: "Certified Pre-Owned", year: 2024, mileage: 25000, fuel: "Gasoline", drivetrain: "FWD", bodyStyle: "SUV", color: "White", img: "assets/vehicles/buick-enclave.jpg", engine: "3.6L V6", horsepower: 310, transmission: "9-Speed Auto", availability: "In Stock", warranty: "6 Years/70k Miles", rating: 4.3 },
    { id: 8, brand: "Cadillac", model: "Escalade", price: 105000, nation: "USA", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "4WD", bodyStyle: "SUV", color: "Black", img: "assets/vehicles/cadillac-escalade.jpg", engine: "6.2L V8", horsepower: 420, transmission: "10-Speed Auto", availability: "In Stock", warranty: "6 Years/70k Miles", rating: 4.6 },
    { id: 9, brand: "Chevrolet", model: "Corvette Z06", price: 125000, nation: "USA", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "RWD", bodyStyle: "Coupe", color: "Red", img: "assets/vehicles/chevrolet-corvette.jpg", engine: "5.5L V8", horsepower: 670, transmission: "8-Speed DCT", availability: "In Stock", warranty: "3 Years/36k Miles", rating: 4.9 },
    { id: 10, brand: "Chrysler", model: "Pacifica", price: 42000, nation: "USA", category: "Car", condition: "Used", year: 2023, mileage: 35000, fuel: "Hybrid", drivetrain: "FWD", bodyStyle: "Van", color: "Gray", img: "https://upload.wikimedia.org/wikipedia/commons/3/3e/2021_Chrysler_Pacifica_Touring_L%2C_front_10.3.20.jpg", engine: "3.6L V6 Hybrid", horsepower: 260, transmission: "eCVT", availability: "In Stock", warranty: "3 Years/36k Miles", rating: 4.2 },
    { id: 11, brand: "Dodge", model: "Challenger SRT Hellcat", price: 78000, nation: "USA", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "RWD", bodyStyle: "Coupe", color: "Black", img: "assets/vehicles/dodge-challenger.jpg", engine: "6.2L Supercharged V8", horsepower: 717, transmission: "6-Speed Manual", availability: "Low Stock", warranty: "3 Years/36k Miles", rating: 4.7 },
    { id: 12, brand: "Ferrari", model: "SF90 Stradale", price: 520000, nation: "Italy", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Plug-in Hybrid", drivetrain: "AWD", bodyStyle: "Coupe", color: "Red", img: "assets/vehicles/ferrari-sf90.jpg", engine: "4.0L Twin Turbo V8 Hybrid", horsepower: 985, transmission: "8-Speed DCT", availability: "Pre-Order", warranty: "3 Years/Unlimited", rating: 5.0 },
    { id: 13, brand: "Ford", model: "Mustang Dark Horse", price: 58000, nation: "USA", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "RWD", bodyStyle: "Coupe", color: "Gray", img: "assets/vehicles/ford-mustang.jpg", engine: "5.0L V8", horsepower: 500, transmission: "10-Speed Auto", availability: "In Stock", warranty: "3 Years/36k Miles", rating: 4.6 },
    { id: 14, brand: "GMC", model: "Sierra Denali", price: 85000, nation: "USA", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Diesel", drivetrain: "4WD", bodyStyle: "Truck", color: "Black", img: "assets/vehicles/ford-f150.jpg", engine: "6.6L Duramax Diesel", horsepower: 470, transmission: "10-Speed Auto", availability: "In Stock", warranty: "5 Years/100k Miles", rating: 4.5 },
    { id: 15, brand: "Honda", model: "Civic Type R", price: 48000, nation: "Japan", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "FWD", bodyStyle: "Hatchback", color: "Red", img: "assets/vehicles/honda-civic-type-r.jpg", engine: "2.0L Turbo", horsepower: 315, transmission: "6-Speed Manual", availability: "In Stock", warranty: "3 Years/36k Miles", rating: 4.7 },
    { id: 16, brand: "Hyundai", model: "Ioniq 5", price: 52000, nation: "South Korea", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Electric", drivetrain: "AWD", bodyStyle: "SUV", color: "Silver", img: "assets/vehicles/hyundai-ioniq5.jpg", engine: "Dual Motor AWD", horsepower: 320, transmission: "1-Speed", availability: "In Stock", warranty: "5 Years/60k Miles", rating: 4.5 },
    { id: 17, brand: "Infiniti", model: "QX80", price: 78000, nation: "Japan", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "4WD", bodyStyle: "SUV", color: "Black", img: "assets/vehicles/infiniti-qx80.jpg", engine: "5.6L V8", horsepower: 400, transmission: "7-Speed Auto", availability: "Low Stock", warranty: "4 Years/60k Miles", rating: 4.4 },
    { id: 18, brand: "Jaguar", model: "F-PACE SVR", price: 95000, nation: "UK", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "AWD", bodyStyle: "SUV", color: "Blue", img: "assets/vehicles/jaguar-fpace.jpg", engine: "5.0L Supercharged V8", horsepower: 542, transmission: "8-Speed Auto", availability: "In Stock", warranty: "5 Years/60k Miles", rating: 4.6 },
    { id: 19, brand: "Jeep", model: "Wrangler Rubicon", price: 55000, nation: "USA", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "4WD", bodyStyle: "SUV", color: "Green", img: "assets/vehicles/jeep-wrangler.jpg", engine: "3.6L V6", horsepower: 285, transmission: "8-Speed Auto", availability: "In Stock", warranty: "3 Years/36k Miles", rating: 4.5 },
    { id: 20, brand: "Kia", model: "EV9", price: 65000, nation: "South Korea", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Electric", drivetrain: "AWD", bodyStyle: "SUV", color: "Silver", img: "assets/vehicles/kia-ev9.jpg", engine: "Dual Motor AWD", horsepower: 380, transmission: "1-Speed", availability: "In Stock", warranty: "5 Years/60k Miles", rating: 4.6 },
    { id: 21, brand: "Lamborghini", model: "Revuelto", price: 600000, nation: "Italy", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Plug-in Hybrid", drivetrain: "AWD", bodyStyle: "Coupe", color: "Yellow", img: "assets/vehicles/lamborghini-revuelto.jpg", engine: "6.5L V12 Hybrid", horsepower: 1001, transmission: "8-Speed DCT", availability: "Pre-Order", warranty: "3 Years/Unlimited", rating: 5.0 },
    { id: 22, brand: "Land Rover", model: "Range Rover Sport", price: 95000, nation: "UK", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "AWD", bodyStyle: "SUV", color: "Black", img: "assets/vehicles/land-rover-rr.jpg", engine: "4.4L Twin Turbo V8", horsepower: 523, transmission: "8-Speed Auto", availability: "Low Stock", warranty: "4 Years/50k Miles", rating: 4.7 },
    { id: 23, brand: "Lexus", model: "LFA", price: 500000, nation: "Japan", category: "Car", condition: "Used", year: 2015, mileage: 15000, fuel: "Gasoline", drivetrain: "RWD", bodyStyle: "Coupe", color: "White", img: "assets/vehicles/lexus-lfa.jpg", engine: "4.8L V10", horsepower: 552, transmission: "6-Speed Auto", availability: "In Stock", warranty: "4 Years/50k Miles", rating: 4.9 },
    { id: 24, brand: "Lotus", model: "Emira", price: 95000, nation: "UK", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "RWD", bodyStyle: "Coupe", color: "Yellow", img: "assets/vehicles/lotus-emira.jpg", engine: "3.5L V6 Supercharged", horsepower: 400, transmission: "6-Speed Manual", availability: "In Stock", warranty: "3 Years/36k Miles", rating: 4.8 },
    { id: 25, brand: "Maserati", model: "MC20", price: 215000, nation: "Italy", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "RWD", bodyStyle: "Coupe", color: "White", img: "assets/vehicles/maserati-mc20.jpg", engine: "3.0L Twin Turbo V6", horsepower: 621, transmission: "8-Speed DCT", availability: "In Stock", warranty: "4 Years/50k Miles", rating: 4.8 },
    { id: 26, brand: "McLaren", model: "750S", price: 320000, nation: "UK", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "RWD", bodyStyle: "Coupe", color: "Orange", img: "assets/vehicles/mclaren-750s.jpg", engine: "4.0L Twin Turbo V8", horsepower: 740, transmission: "7-Speed DCT", availability: "Pre-Order", warranty: "3 Years/Unlimited", rating: 4.9 },
    { id: 27, brand: "Mercedes-AMG", model: "GT Black Series", price: 325000, nation: "Germany", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "RWD", bodyStyle: "Coupe", color: "Black", img: "assets/vehicles/mercedes-amg-gt.jpg", engine: "4.0L Twin Turbo V8", horsepower: 730, transmission: "7-Speed DCT", availability: "Pre-Order", warranty: "3 Years/Unlimited", rating: 4.9 },
    { id: 28, brand: "Mini", model: "JCW GP", price: 45000, nation: "UK", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "FWD", bodyStyle: "Hatchback", color: "Red", img: "assets/vehicles/mini-jcw.jpg", engine: "2.0L Turbo", horsepower: 301, transmission: "8-Speed Auto", availability: "In Stock", warranty: "4 Years/50k Miles", rating: 4.5 },
    { id: 29, brand: "Nissan", model: "GT-R R35", price: 115000, nation: "Japan", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "AWD", bodyStyle: "Coupe", color: "Silver", img: "assets/vehicles/nissan-gtr.jpg", engine: "3.8L Twin Turbo V6", horsepower: 600, transmission: "6-Speed DCT", availability: "In Stock", warranty: "3 Years/36k Miles", rating: 4.7 },
    { id: 30, brand: "Pagani", model: "Utopia", price: 2100000, nation: "Italy", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "RWD", bodyStyle: "Coupe", color: "Blue", img: "assets/vehicles/pagani-utopia.jpg", engine: "6.0L Twin Turbo V12", horsepower: 852, transmission: "7-Speed Manual", availability: "Pre-Order", warranty: "3 Years/Unlimited", rating: 5. },
    { id: 31, brand: "Peugeot", model: "508 PSE", price: 68000, nation: "France", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Plug-in Hybrid", drivetrain: "AWD", bodyStyle: "Sedan", color: "Gray", img: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Peugeot_508_PSE_%282021%29_front.jpg", engine: "2.0L Turbo Hybrid", horsepower: 360, transmission: "8-Speed Auto", availability: "In Stock", warranty: "5 Years/60k Miles", rating: 4.4 },
    { id: 32, brand: "Polestar", model: "Polestar 3", price: 85000, nation: "Sweden", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Electric", drivetrain: "AWD", bodyStyle: "SUV", color: "Black", img: "assets/vehicles/polestar-3.jpg", engine: "Dual Motor AWD", horsepower: 489, transmission: "1-Speed", availability: "In Stock", warranty: "5 Years/60k Miles", rating: 4.6 },
    { id: 33, brand: "Porsche", model: "911 Dakar", price: 165000, nation: "Germany", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "AWD", bodyStyle: "Coupe", color: "Orange", img: "assets/vehicles/porsche-911.jpg", engine: "3.0L Twin Turbo", horsepower: 473, transmission: "8-Speed PDK", availability: "Low Stock", warranty: "4 Years/50k Miles", rating: 4.8 },
    { id: 34, brand: "Ram", model: "1500 TRX", price: 95000, nation: "USA", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "4WD", bodyStyle: "Truck", color: "Green", img: "assets/vehicles/ford-f150.jpg", engine: "6.2L Supercharged V8", horsepower: 702, transmission: "8-Speed Auto", availability: "In Stock", warranty: "5 Years/60k Miles", rating: 4.7 },
    { id: 35, brand: "Renault", model: "Megane RS", price: 48000, nation: "France", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "FWD", bodyStyle: "Hatchback", color: "Yellow", img: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Renault_M%C3%A9gane_RS_Trophy-R_%282019%29_front.jpg", engine: "1.8L Turbo", horsepower: 295, transmission: "6-Speed Manual", availability: "In Stock", warranty: "3 Years/60k Miles", rating: 4.5 },
    { id: 36, brand: "Rolls-Royce", model: "Spectre", price: 420000, nation: "UK", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Electric", drivetrain: "AWD", bodyStyle: "Coupe", color: "White", img: "assets/vehicles/rolls-royce-spectre.jpg", engine: "Dual Motor AWD", horsepower: 577, transmission: "1-Speed", availability: "Low Stock", warranty: "4 Years/Unlimited", rating: 5. },
    { id: 37, brand: "Subaru", model: "WRX STI", price: 50000, nation: "Japan", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "AWD", bodyStyle: "Sedan", color: "Blue", img: "assets/vehicles/subaru-wrx.jpg", engine: "2.5L Turbo", horsepower: 310, transmission: "6-Speed Manual", availability: "In Stock", warranty: "3 Years/36k Miles", rating: 4.6 },
    { id: 38, brand: "Tesla", model: "Model S", price: 125000, nation: "USA", category: "Car", condition: "Used", year: 2020, mileage: 25000, fuel: "Electric", drivetrain: "AWD", bodyStyle: "Sedan", color: "Red", img: "assets/vehicles/tesla-model-s.jpg", engine: "Tri Motor AWD", horsepower: 1020, transmission: "1-Speed", availability: "In Stock", warranty: "4 Years/50k Miles", rating: 4.5 },
    { id: 39, brand: "Toyota", model: "GR Corolla", price: 42000, nation: "Japan", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "AWD", bodyStyle: "Hatchback", color: "White", img: "assets/vehicles/toyota-gr-corolla.jpg", engine: "1.6L Turbo", horsepower: 300, transmission: "6-Speed Manual", availability: "In Stock", warranty: "3 Years/36k Miles", rating: 4.7 },
    { id: 40, brand: "Volkswagen", model: "Golf R", price: 52000, nation: "Germany", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "AWD", bodyStyle: "Hatchback", color: "Blue", img: "assets/vehicles/volkswagen-golf-r.jpg", engine: "2.0L Turbo", horsepower: 315, transmission: "7-Speed DCT", availability: "In Stock", warranty: "4 Years/50k Miles", rating: 4.6 },
    { id: 41, brand: "Volvo", model: "XC90 Recharge", price: 78000, nation: "Sweden", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Plug-in Hybrid", drivetrain: "AWD", bodyStyle: "SUV", color: "Black", img: "assets/vehicles/volvo-xc90.jpg", engine: "2.0L Supercharged Hybrid", horsepower: 455, transmission: "8-Speed Auto", availability: "In Stock", warranty: "4 Years/50k Miles", rating: 4.7 },
    { id: 42, brand: "Lucid", model: "Air Sapphire", price: 249000, nation: "USA", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Electric", drivetrain: "AWD", bodyStyle: "Sedan", color: "Blue", img: "assets/vehicles/lucid-air.jpg", engine: "Tri Motor AWD", horsepower: 1234, transmission: "1-Speed", availability: "Pre-Order", warranty: "4 Years/50k Miles", rating: 4.9 },
    { id: 43, brand: "Rimac", model: "Nevera", price: 2200000, nation: "Croatia", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Electric", drivetrain: "AWD", bodyStyle: "Coupe", color: "Black", img: "assets/vehicles/rimac-nevera.jpg", engine: "Quad Motor AWD", horsepower: 1914, transmission: "1-Speed", availability: "Pre-Order", warranty: "3 Years/Unlimited", rating: 5. },
    { id: 44, brand: "Pininfarina", model: "Battista", price: 2200000, nation: "Italy", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Electric", drivetrain: "AWD", bodyStyle: "Coupe", color: "Red", img: "assets/vehicles/pininfarina-battista.jpg", engine: "Quad Motor AWD", horsepower: 1900, transmission: "1-Speed", availability: "Pre-Order", warranty: "3 Years/Unlimited", rating: 5. },
    { id: 45, brand: "Hennessey", model: "Venom F5", price: 1800000, nation: "USA", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "RWD", bodyStyle: "Coupe", color: "Black", img: "assets/vehicles/hennessey-venom.jpg", engine: "6.6L Twin Turbo V8", horsepower: 1842, transmission: "6-Speed DCT", availability: "Pre-Order", warranty: "3 Years/36k Miles", rating: 5. },
    { id: 46, brand: "Ferrari", model: "Daytona SP3", price: 2200000, nation: "Italy", category: "Car", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "RWD", bodyStyle: "Coupe", color: "Red", img: "assets/vehicles/ferrari-daytona.jpg", engine: "6.5L V12", horsepower: 840, transmission: "8-Speed DCT", availability: "Pre-Order", warranty: "3 Years/Unlimited", rating: 5. },
    // Bikes (4)
    { id: 47, brand: "Ducati", model: "Panigale V4 R", price: 42000, nation: "Italy", category: "Bike", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "RWD", bodyStyle: "Sport", color: "Red", img: "assets/vehicles/ducati-panigale.jpg", engine: "999cc V4", horsepower: 234, transmission: "6-Speed", availability: "Low Stock", warranty: "2 Years/Unlimited", rating: 4.9 },
    { id: 48, brand: "Yamaha", model: "YZF-R1M", price: 28000, nation: "Japan", category: "Bike", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "RWD", bodyStyle: "Sport", color: "Blue", img: "assets/vehicles/yamaha-r1.jpg", engine: "998cc Inline-4", horsepower: 200, transmission: "6-Speed", availability: "In Stock", warranty: "2 Years/20k Miles", rating: 4.8 },
    { id: 49, brand: "Kawasaki", model: "Ninja ZX-10RR", price: 32000, nation: "Japan", category: "Bike", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "RWD", bodyStyle: "Sport", color: "Green", img: "assets/vehicles/kawasaki-ninja.jpg", engine: "998cc Inline-4", horsepower: 204, transmission: "6-Speed", availability: "In Stock", warranty: "2 Years/Unlimited", rating: 4.7 },
    { id: 50, brand: "BMW", model: "M1000 RR", price: 35000, nation: "Germany", category: "Bike", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "RWD", bodyStyle: "Sport", color: "Black", img: "assets/vehicles/bmw-m1000rr.jpg", engine: "999cc Inline-4", horsepower: 205, transmission: "6-Speed", availability: "In Stock", warranty: "3 Years/Unlimited", rating: 4.8 },
    // Buses (4)
    { id: 51, brand: "Mercedes-Benz", model: "Citaro", price: 350000, nation: "Germany", category: "Bus", condition: "New", year: 2026, mileage: 0, fuel: "Diesel", drivetrain: "RWD", bodyStyle: "City Bus", color: "White", img: "assets/vehicles/mercedes-citaro.jpg", engine: "7.7L Diesel", horsepower: 354, transmission: "6-Speed Auto", availability: "In Stock", warranty: "3 Years/100k Miles", rating: 4.5 },
    { id: 52, brand: "Volvo", model: "9700", price: 420000, nation: "Sweden", category: "Bus", condition: "New", year: 2026, mileage: 0, fuel: "Diesel", drivetrain: "RWD", bodyStyle: "Coach", color: "Blue", img: "assets/vehicles/volvo-9700.jpg", engine: "12.8L Diesel", horsepower: 460, transmission: "8-Speed Auto", availability: "In Stock", warranty: "3 Years/150k Miles", rating: 4.7 },
    { id: 53, brand: "Scania", model: "K series", price: 380000, nation: "Sweden", category: "Bus", condition: "New", year: 2026, mileage: 0, fuel: "Diesel", drivetrain: "RWD", bodyStyle: "Coach", color: "White", img: "assets/vehicles/volvo-9700.jpg", engine: "12.4L Diesel", horsepower: 410, transmission: "8-Speed Auto", availability: "Low Stock", warranty: "3 Years/100k Miles", rating: 4.6 },
    { id: 54, brand: "MAN", model: "Lion's Coach", price: 390000, nation: "Germany", category: "Bus", condition: "New", year: 2026, mileage: 0, fuel: "Diesel", drivetrain: "RWD", bodyStyle: "Coach", color: "Yellow", img: "assets/vehicles/mercedes-citaro.jpg", engine: "12.4L Diesel", horsepower: 420, transmission: "8-Speed Auto", availability: "In Stock", warranty: "3 Years/150k Miles", rating: 4.6 },
    // Trucks (4)
    { id: 55, brand: "Freightliner", model: "Cascadia", price: 420000, nation: "USA", category: "Truck", condition: "New", year: 2026, mileage: 0, fuel: "Diesel", drivetrain: "RWD", bodyStyle: "Semi", color: "Black", img: "assets/vehicles/ford-f150.jpg", engine: "12.7L Diesel", horsepower: 475, transmission: "10-Speed Auto", availability: "In Stock", warranty: "5 Years/200k Miles", rating: 4.8 },
    { id: 56, brand: "Peterbilt", model: "579", price: 450000, nation: "USA", category: "Truck", condition: "New", year: 2026, mileage: 0, fuel: "Diesel", drivetrain: "RWD", bodyStyle: "Semi", color: "Red", img: "assets/vehicles/ford-f150.jpg", engine: "12.9L Diesel", horsepower: 500, transmission: "10-Speed Auto", availability: "In Stock", warranty: "5 Years/200k Miles", rating: 4.7 },
    { id: 57, brand: "Kenworth", model: "T680", price: 430000, nation: "USA", category: "Truck", condition: "New", year: 2026, mileage: 0, fuel: "Diesel", drivetrain: "RWD", bodyStyle: "Semi", color: "Blue", img: "assets/vehicles/ford-f150.jpg", engine: "12.9L Diesel", horsepower: 455, transmission: "10-Speed Auto", availability: "In Stock", warranty: "5 Years/200k Miles", rating: 4.7 },
    { id: 58, brand: "Ford", model: "F-650", price: 125000, nation: "USA", category: "Truck", condition: "New", year: 2026, mileage: 0, fuel: "Diesel", drivetrain: "RWD", bodyStyle: "Box Truck", color: "White", img: "assets/vehicles/ford-f150.jpg", engine: "6.7L Diesel", horsepower: 350, transmission: "6-Speed Auto", availability: "In Stock", warranty: "4 Years/150k Miles", rating: 4.6 },
    // Vans (4)
    { id: 59, brand: "Ram", model: "ProMaster", price: 95000, nation: "USA", category: "Van", condition: "New", year: 2026, mileage: 0, fuel: "Diesel", drivetrain: "FWD", bodyStyle: "Cargo Van", color: "White", img: "assets/vehicles/ford-f150.jpg", engine: "3.0L Diesel", horsepower: 175, transmission: "6-Speed Auto", availability: "In Stock", warranty: "3 Years/100k Miles", rating: 4.4 },
    { id: 60, brand: "Mercedes-Benz", model: "Sprinter", price: 75000, nation: "Germany", category: "Van", condition: "New", year: 2026, mileage: 0, fuel: "Diesel", drivetrain: "RWD", bodyStyle: "Cargo Van", color: "White", img: "assets/vehicles/mercedes-sprinter.jpg", engine: "3.0L Diesel", horsepower: 188, transmission: "7-Speed Auto", availability: "In Stock", warranty: "3 Years/100k Miles", rating: 4.6 },
    { id: 61, brand: "Ford", model: "Transit", price: 65000, nation: "USA", category: "Van", condition: "New", year: 2026, mileage: 0, fuel: "Diesel", drivetrain: "RWD", bodyStyle: "Cargo Van", color: "White", img: "assets/vehicles/ford-f150.jpg", engine: "3.5L V6", horsepower: 275, transmission: "10-Speed Auto", availability: "In Stock", warranty: "3 Years/100k Miles", rating: 4.5 },
    { id: 62, brand: "RAM", model: "ProMaster City", price: 55000, nation: "USA", category: "Van", condition: "New", year: 2026, mileage: 0, fuel: "Gasoline", drivetrain: "FWD", bodyStyle: "Cargo Van", color: "White", img: "assets/vehicles/ford-f150.jpg", engine: "3.6L V6", horsepower: 285, transmission: "6-Speed Auto", availability: "In Stock", warranty: "3 Years/100k Miles", rating: 4.4 }
];

const insert = db.prepare(`
    INSERT INTO listings (brand, model, price, nation, category, condition, body_style, fuel_type, drivetrain, color, city, image, badges, specs, rating)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`);

console.log('Populating database with', inventory.length, 'listings...');

for (const item of inventory) {
    insert.run(
        item.brand,
        item.model,
        item.price,
        item.nation,
        item.category,
        item.condition,
        item.bodyStyle,
        item.fuel,
        item.drivetrain,
        item.color,
        item.city || 'Nairobi',
        item.img,
        JSON.stringify([]),
        JSON.stringify(item.specs || {}),
        item.rating
    );
}

const count = db.prepare('SELECT COUNT(*) as c FROM listings').get();
console.log('Successfully populated', count.c, 'listings');
